/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:39909a4d-7c59-4cf1-a283-8e1ca17b16b7",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_7c0cVw8AZ",
    "aws_user_pools_web_client_id": "6e8vdkk4rqm530apu8k4sih13n",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://kznptokyofezpei4bc2l6pgafi.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jstf2sjibnf3hbiud7wh4wseca",
    "aws_user_files_s3_bucket": "mowo151735-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
